apiVersion: v1
data:
  functions.helloworld.default: X3k3T1JQcnlRMHRQLXdNX1NfQm5RaTZKbDNMY1R6dEw2Zkdod0pxNVFOdjNBekZ1SUV6RUpnPT0=
  host.function.default: WmFzNkxDWnRha1lZSUFHMEphS05SbHJwYkxYMEdiMHg5Wkp4XzNyUG1jeUVBekZ1QUx6eG53PT0=
  host.master: ckhTb1dXNlpEWDE4Qm9wYjdjVWRtNWo2eVFsd0lwQkJTWXUweFJlNFdEdzRBekZ1SHJvdUxBPT0=
  host.systemKey.default: cFhsV1QzalRKaExKOEhnQWtiY2RmMTZPUmNWTW5QN2ZSTHRfRFpoOWtOX21BekZ1OEZPMU93PT0=
kind: Secret
metadata:
  name: func-keys-kube-secret-function-helloworld
  namespace: ingress-nginx
type: Opaque
