apiVersion: v1
data:
  AzureWebJobsStorage: VXNlRGV2ZWxvcG1lbnRTdG9yYWdlPXRydWU=
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0
kind: Secret
metadata:
  name: function-helloworld
  namespace: ingress-nginx
type: Opaque
